#!/bin/env sh

cd /tmp/archlinux-steamlink

mkdir -p old-root
pivot_root . old-root
chroot .

mount --bind /old-root/dev /dev
mount tmpfs -t tmpfs /run
mount tmpfs -t tmpfs /tmp
touch /dev/sda
touch /dev/sda1
mount --bind /dev/block/sda /dev/sda
mount --bind /dev/block/sda1 /dev/sda1

ln -s /old-root/lib/modules/*-mrvl /lib/modules/ || true

exec lib/systemd/systemd --log-target=kmsg --log-level=info
